server:
  servlet:
    context-path: /lemon
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api-runner 
    username: root
    password: root
logging:
  level:
    root: info
    com.lemon.mapper: trace
    